language: c
install: bash build/prepare.sh
script:
- make readme
- make html
notifications:
  email:
    on_success: always
    on_failure: always
after_success: bash build/update_pages.sh
before_deploy: bash build/build_pdf.sh
deploy:
  provider: releases
  api_key:
    secure: c6QzpYXgUaF9YGno01+32F6d52EuvcWZ8JE03IZGZ5R6LcJpYV3qUELLrYXSaPq8aKAG4ZVb6KnTM/x5Rr2p8V9YZ5AAS+Smma7TL0vY+aecNeFHU/jwtq7gdlaM4Jj4KnYLLiOTz+fCLoQNqa5jDCr6gmEZD/hNyQyqYRQi+Us=
  file: Vaibhav_Sagar_resume.pdf
  on:
    repo: vaibhavsagar/resumate
    all_branches: true
    tags: true
env:
  global:
  - secure: JnWODDh59QKkmb9hdWAtqXiyNXturn+K4rNsobfQKTUHCwW/0D0po8ex6t4230RZnJc/P505338t0YYLka3pp6hl0x4bOXG23au/7G92AQtKBcaiP9LzhdQZYGSQvYjRu1sNld2zN/CFgZtdVXgkC6Ox651c++qK8i87GC/QBbY=
